languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "http://sdugaoxiang.github.io/"
canonifyurls = true


title = "Xiang"
author = "Gao Xiang"

[params]
    author_name = "Gao Xiang"
    twitter_username = "chibicode"
    gravatar_id = "d747ad92018acd87a77899704fc6693d"
